//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PxLanguagePlugin.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PxLanguagePlugin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///
        ///  &quot;excludedWords&quot;: [
        ///    &quot;the&quot;,
        ///    &quot;an&quot;,
        ///    &quot;a&quot;,
        ///    &quot;of&quot;,
        ///    &quot;in&quot;,
        ///    &quot;to&quot;,
        ///    &quot;for&quot;,
        ///    &quot;with&quot;,
        ///    &quot;on&quot;,
        ///    &quot;at&quot;,
        ///    &quot;from&quot;,
        ///    &quot;by&quot;,
        ///    &quot;about&quot;,
        ///    &quot;as&quot;,
        ///    &quot;into&quot;,
        ///    &quot;like&quot;,
        ///    &quot;through&quot;,
        ///    &quot;after&quot;,
        ///    &quot;over&quot;,
        ///    &quot;between&quot;,
        ///    &quot;out&quot;,
        ///    &quot;against&quot;,
        ///    &quot;during&quot;,
        ///    &quot;without&quot;,
        ///    &quot;before&quot;,
        ///    &quot;under&quot;,
        ///    &quot;around&quot;,
        ///    &quot;among&quot;,
        ///    &quot;and&quot;,
        ///    &quot;or&quot;,
        ///    &quot;how&quot;,
        ///    &quot;where&quot;,
        ///    &quot;what&quot;,
        ///    &quot;why&quot;,
        ///    &quot;when&quot;,
        ///    &quot;who&quot;,
        ///    &quot;which&quot;,
        ///    &quot;muc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string keywordMetadata {
            get {
                return ResourceManager.GetString("keywordMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;static&quot;: {
        ///    &quot;release&quot;: &quot;Release&quot;,
        ///    &quot;all-groups&quot;: &quot;All Groups&quot;
        ///  },
        ///  &quot;error&quot;: {
        ///    &quot;authentication&quot;: &quot;Invalid authentication. Access denied.&quot;,
        ///    &quot;create&quot;: &quot;No record has been created. Please review your input.&quot;,
        ///    &quot;delete&quot;: &quot;No record has been deleted. Please review your selection.&quot;,
        ///    &quot;duplicate&quot;: &quot;No record has been created. A duplicate record already exists. Please review your input.&quot;,
        ///    &quot;exception&quot;: &quot;An unexpected error has occurred. Please seek technical support.&quot;,
        ///    &quot;i [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{
        ///&quot;match&quot;: &quot;angstrom&quot;,
        ///&quot;lemma&quot;: &quot;a&quot;
        ///}
        ///,{
        ///&quot;match&quot;: &quot;axerophthol&quot;,
        ///&quot;lemma&quot;: &quot;a&quot;
        ///}
        ///,{
        ///&quot;match&quot;: &quot;adenine&quot;,
        ///&quot;lemma&quot;: &quot;a&quot;
        ///}
        ///,{
        ///&quot;match&quot;: &quot;ampere&quot;,
        ///&quot;lemma&quot;: &quot;a&quot;
        ///}
        ///,{
        ///&quot;match&quot;: &quot;amp&quot;,
        ///&quot;lemma&quot;: &quot;a&quot;
        ///}
        ///,{
        ///&quot;match&quot;: &quot;AA&quot;,
        ///&quot;lemma&quot;: &quot;aa&quot;
        ///}
        ///,{
        ///&quot;match&quot;: &quot;aa&quot;,
        ///&quot;lemma&quot;: &quot;aa&quot;
        ///}
        ///,{
        ///&quot;match&quot;: &quot;AAA&quot;,
        ///&quot;lemma&quot;: &quot;aaa&quot;
        ///}
        ///,{
        ///&quot;match&quot;: &quot;AAC&quot;,
        ///&quot;lemma&quot;: &quot;aac&quot;
        ///}
        ///,{
        ///&quot;match&quot;: &quot;Aachen&quot;,
        ///&quot;lemma&quot;: &quot;aachen&quot;
        ///}
        ///,{
        ///&quot;match&quot;: &quot;Aken&quot;,
        ///&quot;lemma&quot;: &quot;aachen&quot;
        ///}
        ///,{
        ///&quot;match&quot;: &quot;Chapelle&quot;,
        ///&quot;lemma&quot;: &quot;aachen&quot;
        ///}
        ///,{
        ///&quot;mat [rest of string was tru....
        /// </summary>
        internal static string synonym {
            get {
                return ResourceManager.GetString("synonym", resourceCulture);
            }
        }
    }
}
